#core npm
alias npinit='npm init'
alias npinity='npm init -y'
alias npi='npm install '
alias npis='npm install --save '
alias npid='npm install --save-dev '
alias npiD='npm install -D '
alias npig='npm install -g '
alias npu='npm uninstall '
alias npus='npm uninstall --save '
alias npud='npm uninstall --save-dev '
alias npug='npm uninstall -g '
alias npuall='npm uninstall $(ls -1 node_modules | tr "/\n" " ")'
alias npuallg='npm uninstall -g $(npm -g ls --depth=0 | grep -v "npm@")'
alias npualll='npm uninstall $(ls -1 node_modules | tr "/\n" " ") && npm install'
alias npd='npm run dev'
alias nps='npm run start'
alias npb='npm run build'
alias npt='npm run test'
alias npw='npm run watch'

# nuxt npx
alias nuxt='npx create-nuxt-app'
alias naddc='npx nuxi add component '
alias naddp='npx nuxi add page '
alias naddl='npx nuxi add layout '
alias naddm='npx nuxi add middleware '
alias naddpl='npx nuxi add plugin '
alias naddst='npx nuxi add store '
alias naddu='npx nuxi add util '



#Git
alias gi='git init'
alias gcl='git clone '
alias gadd='git add '
alias gcommit='git commit -m '
alias gpush='git push '
alias gpull='git pull '
alias gstatus='git status '
alias glog='git log '
alias gdiff='git diff '
alias gbranch='git branch '
alias gcheckout='git checkout '
alias gmerge='git merge '
alias greset='git reset '
alias gresetH='git reset --hard '
alias gresetS='git reset --soft '
alias gresetM='git reset --mixed '
alias gcherry='git cherry-pick '
alias gfetch='git fetch '
alias gtag='git tag '
alias gshow='git show '
alias gclean='git clean -f '   
alias grevert='git revert '
alias gremote='git remote '
alias gremoteadd='git remote add '
alias gsubmodule='git submodule '

# Utils
alias c='clear'
alias h='history'
alias j='jobs'
alias p='pwd'
alias l='ls -l'
alias ll='ls -la'
alias la='ls -a'
alias lt='ls -lt'
alias lrt='ls -lrt'
alias t='touch '
alias m='mkdir '

# Vite
alias vite='npx vite'
alias viteb='npx vite build'
alias vitebdev='npx vite build --mode development'
alias vitebprod='npx vite build --mode production'
alias vitebtest='npx vite build --mode test'
alias vitecreate='npm create vite@latest'
alias vitevue='npm create vite@latest --template vue'
alias vitevue3='npm create vite@latest --template vue-ts'
alias vitevue3ts='npm create vite@latest --template vue-ts'
alias vitereact='npm create vite@latest --template react'
alias vitereactts='npm create vite@latest --template react-ts'
alias vitepreact='npm create vite@latest --template preact'
alias vitepreactts='npm create vite@latest --template preact-ts'
alias vitevanilla='npm create vite@latest --template vanilla'
alias vitevanillats='npm create vite@latest --template vanilla-ts'


# Laravel
alias laravel='laravel new '
alias lserve='php artisan serve'
alias lmigrate='php artisan migrate'
alias lmigratef='php artisan migrate:fresh'
alias lmigratefs='php artisan migrate:fresh --seed'
alias lmigratefsr='php artisan migrate:fresh --seed --seeder='
alias lcontroller='php artisan make:controller '
alias lmodel='php artisan make:model '
alias lfactory='php artisan make:factory '
alias lseeder='php artisan make:seeder '
alias ltest='php artisan make:test '
alias lrequest='php artisan make:request '
alias lresource='php artisan make:resource '
alias lmail='php artisan make:mail '
alias lnotification='php artisan make:notification '
alias ljob='php artisan make:job '
alias levent='php artisan make:event '
alias llistener='php artisan make:listener '
alias lmiddleware='php artisan make:middleware '
alias lprovider='php artisan make:provider '
alias lcommand='php artisan make:command '
alias lcomponent='php artisan make:component '
alias lchannel='php artisan make:channel '
alias lpolicy='php artisan make:policy '
alias lrule='php artisan make:rule '
alias lconsole='php artisan make:console '
